### ISSUE TITLE
[BUG] Icon Links Don't work on https://www.eddiejaoude.io

### ISSUE THREAD

**Issue by henriwoodcock** [eddiejaoude/eddiejaoude#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Note: Sorry not sure if this is the right place to put this but cannot find the repository for your website.

The 4 icons at the bottom of https://www.eddiejaoude.io do not work on either Safari or Chrome. On inspect element I cannot see a link to the social media websites.

<img width="524" alt="Screenshot 2021-07-28 at 18 03 26" src="https://user-images.githubusercontent.com/45004378/127365534-9606e57a-99d7-46e2-bd58-ba87332b3384.png">

### Expected Behavior

To take you to the respective website.

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by eddiejaoude** [comment]
oh you are right 😱 thank you for raising

**Comment by eddiejaoude** [comment]
This should now be fixed, thank you again for raising the issue 👍
