### ISSUE TITLE
Minor grammatical changes / suggestions

### ISSUE THREAD

**Issue by cpjworks** [eddiejaoude/eddiejaoude#116]
Hi Eddie,

I just watched your freeCodeCamp YouTube video, [Complete Guide to Open Source - How to Contribute](https://youtu.be/yzeVMecydCE), and really enjoyed it. As per your advice, please find below my first raised issue. Your README is visually appealing and informative, but here are a few small grammatical changes I would suggest to make it even easier to read. The differences are highlighted in **bold**.

Before:
> I believe Open Source is for EVERYONE, yes YOU TOO! Join me on my [YouTube channel](http://youtube.com/eddiejaoude?sub_confirmation=1) so we can geek out on Videos and Live streams 🎥
...
📰 Sign up to my community [newsletter](http://eddiejaoude.io/newsletters) to be kept up-to-date monthly with upcoming events, community achievements and more

After:
> I believe Open Source is for **EVERYONE; yes, YOU TOO**! Join me on my [YouTube channel](http://youtube.com/eddiejaoude?sub_confirmation=1) so we can geek out on Videos and Live streams 🎥
...
📰 Sign up to my **monthly** community [newsletter](http://eddiejaoude.io/newsletters) to be kept up-to-date with upcoming events, community achievements and more

Summary: 
- Add a semi-colon after "EVERYONE" and a comma after "yes". 
- Move "monthly" to an earlier location in the sentence.

Thank you,

Chris

PS: This is my first ever comment / issue here on GitHub, so please forgive me for not formatting this with the diff comparison.

**Comment by eddiejaoude** [comment]
Thank you Chris! These are great 👍 

Do you want to raise a Pull Request with these changes?

Btw you can also do `diffs` with code blocks, that look like...

```diff
- I believe Open Source is for EVERYONE; yes, YOU TOO! Join me on my [YouTube channel](http://youtube.com/eddiejaoude?sub_confirmation=1) so we can geek out on Videos and Live streams
+ I believe Open Source is for **EVERYONE; yes, YOU TOO!** Join me on my [YouTube channel](http://youtube.com/eddiejaoude?sub_confirmation=1) so we can geek out on Videos and Live streams
```

**Comment by cpjworks** [comment]
Hi Eddie,

Thanks for the reply. I checked the Pull requests tab, and clicked "New pull request", but cannot see an option to open a new fork, apologies. It redirects me [here](https://github.com/eddiejaoude/eddiejaoude/compare), with the green "Create pull request" button greyed out. Please find the diff code below. I think you can accept these changes directly from here?

```diff
- I believe Open Source is for EVERYONE, yes YOU TOO! Join me on my [YouTube channel](http://youtube.com/eddiejaoude?sub_confirmation=1) so we can geek out on Videos and Live streams 🎥
+ I believe Open Source is for EVERYONE; yes, YOU TOO! Join me on my [YouTube channel](http://youtube.com/eddiejaoude?sub_confirmation=1) so we can geek out on Videos and Live streams 🎥
```

```diff
- 📰 Sign up to my community [newsletter](http://eddiejaoude.io/newsletters) to be kept up-to-date monthly with upcoming events, community achievements and more
+ 📰 Sign up to my monthly community [newsletter](http://eddiejaoude.io/newsletters) to be kept up-to-date with upcoming events, community achievements and more
```

**Comment by eddiejaoude** [comment]
Before creating the pull request you will need to make the changes, you can do this by pressing the ✏️ icon on the file you are viewing

Then 
1. make the changes
2. commit at the bottom of the page
3. make the new pull request

You might want to come and chat to our open source community EddieHub, the members are super supportive and can give you realtime help http://discord.eddiehub.org

**Comment by cpjworks** [comment]
Hi Eddie,

Thank you. I tried it, so fingers crossed it's all correct and works.

Chris

**Comment by eddiejaoude** [comment]
Looks great! Merged 🎉 Thank you Chris!

https://github.com/eddiejaoude/eddiejaoude/pull/117
