### ISSUE TITLE
[BUG] YouTube videos github actions fail

### ISSUE THREAD

**Issue by kabir0x23** [eddiejaoude/eddiejaoude#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/44284877/179436805-fda74882-92b0-4235-ba71-a4b4dc5c1d37.png)

Error:
![image](https://user-images.githubusercontent.com/44284877/179436893-636d7bed-ce04-4212-8e2a-ecebd9f3fa6b.png)

Error link:
https://github.com/eddiejaoude/eddiejaoude/runs/7381745143?check_suite_focus=true

working fine in my forked repo
![image](https://user-images.githubusercontent.com/44284877/179436881-18ecb0b8-448b-4574-a000-8702d4e7b8a8.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by eddiejaoude** [comment]
Thank you! This has now been fixed
