### ISSUE TITLE
Readmefile improvement: create a section for open source repos

### ISSUE THREAD

**Issue by CBID2** [eddiejaoude/eddiejaoude#126]
Create a specific section where you pin examples of open source repos @eddiejaoude

**Comment by bhavya2021245** [comment]
Can I work on this issue I will make the template for it where @eddiejaoude can make changes?

**Comment by eddiejaoude** [comment]
Thank you. I think I will close this issue as I have pinned repos in my profile 

Come and geek out with us in EddieHub, I am working full time on the LinkFree repo, hopefully see you there
