### ISSUE TITLE
Open a repo to upload project ideas for others to get inspiration

### ISSUE THREAD

**Issue by AbdhullahAfthah** [eddiejaoude/eddiejaoude#129]
Bunnie and you were talking about this in the YouTube livestream. I personally would love to see such a repository

**Comment by ATREAY** [comment]
Hey @AbdhullahAfthah, it's Atreay! I've already got a repo called [openBookmarkz](https://github.com/openBookmarkz/ideas) for this. You're welcome to hop in and contribute. And @eddiejaoude, if you're vibing with this idea too, we'd be totally down to team up!

**Comment by eddiejaoude** [comment]
Thank you for raising. I will close for now due to a lack of activity
