### ISSUE TITLE
Move stats to the right, so active is on the left

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/eddiejaoude#13]

**Comment by rhianeKobar** [comment]
what do you mean by active?

**Comment by eddiejaoude** [comment]
I wish I made more notes on this at the time, because now I can not remember 🤦‍♂️ . My profile has changed a lot since this issue was created. It is probably best I close it and we can create new issues for any new ideas we have. Thank you for nudging me on this 👍
