### ISSUE TITLE
[REFACTOR] Linkfree website url location

### ISSUE THREAD

**Issue by ErtanTaner** [eddiejaoude/eddiejaoude#132]
I think you should change your Linkfree's website url from bottom to here:
![Screenshot from 2023-01-18 09-33-58](https://user-images.githubusercontent.com/62712555/213101103-db7d9ba1-2f17-4fb1-9042-45e584460952.png)

It's a crossroad for your portfolio and hard to see when open the profile, easily missable.

**Comment by eddiejaoude** [comment]
Thank you 👍
