### ISSUE TITLE
Setting up Contributors Guidelines

### ISSUE THREAD

**Issue by katzjeff** [eddiejaoude/eddiejaoude#137]
Hi Eddie
It would be great setting up some guidelines for contributors.  While it might seem "overboard" for a profile, a structured approach to any project creates room for great work as it aligns all within a set of rules . 
Part of this would fall under the documentation labels.

**Comment by katzjeff** [comment]
> thanks for raising! this project doesn't have many contributors, so I will close - come and join us in LinkFree it is a very active project https://github.com/EddieHubCommunity/LinkFree

Thanks for the response, sure will join you on the LinkFree project.

**Comment by eddiejaoude** [comment]
Great, see you there!
