### ISSUE TITLE
I would like add a testimonial to your profile.

### ISSUE THREAD

**Issue by syedr-prog** [eddiejaoude/eddiejaoude#140]
I watched an open source tutorial on free code camp on how to contribute to open source and I would like to add a testimonial if you'd like.
```Diff
+ Eddie has inspired me to add to open source community by creating an amazing video tutorial on open source. Eddie also have a community that inspires people to add to the open source projects
```

**Comment by eddiejaoude** [comment]
Thank you 👍  If you could add it on the LinkFree repo please, here is the link https://github.com/EddieHubCommunity/LinkFree/issues/new?labels=testimonial&template=testimonial.yml&title=New+Testimonial+for+Eddie%20Jaoude&name=eddiejaoude
