### ISSUE TITLE
url: change linkfree to biodrop 

### ISSUE THREAD

**Issue by vinzvinci** [eddiejaoude/eddiejaoude#141]
Hi Eddie, you are still using old link
![image](https://github.com/eddiejaoude/eddiejaoude/assets/73097560/7a868611-3e64-4177-a564-d96512e13851)

I want to change to: https://www.biodrop.io/eddiejaoude

**Comment by vinzvinci** [comment]
fix: https://github.com/eddiejaoude/eddiejaoude/commit/b10305a8c370c7ce33f74058ad365b5c7edcafa4

closing this

**Comment by eddiejaoude** [comment]
Sorry I missed this @vinzvinci

**Comment by vinzvinci** [comment]
> Sorry I missed this @vinzvinci

No worries. I know you have so many notifs. ^^
