### ISSUE TITLE
[BUG] Remove newsletter and replace with digital products

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/eddiejaoude#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the list newsletter url exists

### Expected Behavior

Replace newsletter url with digital products url https://products.eddiejaoude.io

### What browsers are you seeing the problem on?

Safari

**Comment by Vijaykv5** [comment]
let me give a try @eddiejaoude

**Comment by eddiejaoude** [comment]
Sorry I missed your comment @Vijaykv5

**Comment by Vijaykv5** [comment]
no issues @eddiejaoude
