### ISSUE TITLE
Markdown video

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/eddiejaoude#45]
# Heading 1
###### Heading 6

This is **bold** text
This is *italic* text
This is ~~strike through~~ text

| Column 1 | Column 2 | Column 3 | Column 4 |
| :--- | :---: | ---: | ---: |
| Row 1a | Row 1b | Row 1c | Row 1d |
| Row 2a | Row 2b | Row 2c |Row 2d |

```ts
const timezones = [
    { abbr: 'PDT', zone: 'America/Los_Angeles' },
    { abbr: 'MST', zone: 'America/Creston' },
    { abbr: 'EST', zone: 'America/Panama' },
    { abbr: 'ADT', zone: 'America/Halifax' },

    { abbr: 'UTC', zone: 'Europe/London' },
    { abbr: 'UK', zone: 'Europe/London' },
    { abbr: 'CEST', zone: 'Europe/Stockholm' },
    { abbr: 'EET', zone: 'Europe/Finland' },
 ];
```

```diff
const timezones = [
    { abbr: 'PDT', zone: 'America/Los_Angeles' },
    { abbr: 'MST', zone: 'America/Creston' },
    { abbr: 'EST', zone: 'America/Panama' },
-    { abbr: 'ADT', zone: 'America/Hali' },
+    { abbr: 'ADT', zone: 'America/Halifax' },

    { abbr: 'UTC', zone: 'Europe/London' },
    { abbr: 'UK', zone: 'Europe/London' },
    { abbr: 'CEST', zone: 'Europe/Stockholm' },
    { abbr: 'EET', zone: 'Europe/Finland' },
 ];
```

1. Item 1
1. Item 2
1. Item 3
1. Item 4

- [x] Item 1
- [ ] Item 2
- [ ] Item 3
- [ ] Item 4

> this was our discussion before

Following our discussion I agree we should do it

--- 

Anything else to include?

**Comment by sahilinjaipur** [comment]
blockquote 
> A blockquote would looks great and can go with other items as well.

**Comment by eddiejaoude** [comment]
yep that is another good one, thanks @sahilinjaipur 👍

**Comment by dumbcoder7** [comment]
Oh my, thought this was a real issue or something

**Comment by eddiejaoude** [comment]
oops I should come this now. Thanks @dumbcoder7 👍
