### ISSUE TITLE
Adjust the height of the GitHub stats and the most used lenguages.

### ISSUE THREAD

**Issue by Frakko** [eddiejaoude/eddiejaoude#46]
**This is how it currently looks like:**
<img src="https://user-images.githubusercontent.com/61921998/102687804-1418e900-41f2-11eb-8dcc-84d020ad95d8.png" width="60%">

**My suggestion is to make them have the same height (if possible).**

**Comment by vinzvinci98** [comment]
You could add `&line_height=48"` there eddie

example:
```
tokyonight&line_height=48
```

It doesn't matter if their height is not the same but at least near height.

**Comment by eddiejaoude** [comment]
Thank you @Frakko for raising!!

Thank you @vinzvinci98 for the solution 👍 

<img width="1277" alt="Screenshot 2020-12-28 at 09 03 56" src="https://user-images.githubusercontent.com/624760/103202911-a5bbe100-48eb-11eb-9f63-0fd25b946013.png">
