### ISSUE TITLE
Invalid next to Youtube 

### ISSUE THREAD

**Issue by vinzvinci98** [eddiejaoude/eddiejaoude#47]
I just noticed. Look at the red circle below, it saids the youtube is invalid. Maybe fix that later eddie when you're free :)

![eddie](https://user-images.githubusercontent.com/73097560/102972276-c1169d00-4535-11eb-9d04-e5bb4ef0bd0c.png)

**Comment by eddiejaoude** [comment]
Ahhhh 😱 ! thank you!! 👍

**Comment by eddiejaoude** [comment]
Oh it seems to be working again without any change 🤔 - I will have to keep an eye on it

<img width="641" alt="Screenshot 2020-12-28 at 08 52 47" src="https://user-images.githubusercontent.com/624760/103202367-1cf07580-48ea-11eb-9a80-8f91649c2bae.png">
