### ISSUE TITLE
Cards heights mismatched

### ISSUE THREAD

**Issue by adityaraute** [eddiejaoude/eddiejaoude#49]
When I arrive on the [profile page](https://github.com/eddiejaoude)
This is what I see:
![image](https://user-images.githubusercontent.com/43912470/104751275-32cfb880-577b-11eb-9b59-b14136e2bb4f.png)

When I arrive on the [repository page](https://github.com/eddiejaoude/eddiejaoude)
Again, this is what I see:
![image](https://user-images.githubusercontent.com/43912470/104751354-4aa73c80-577b-11eb-9113-f64255c31d0c.png)

But when I arrive on the [Readme page](https://github.com/eddiejaoude/eddiejaoude/blob/master/README.md)
I see the cards aligned well in height thus:
![image](https://user-images.githubusercontent.com/43912470/104751453-690d3800-577b-11eb-981b-2b699a13cb10.png)

What's going wrong? Surely, this must change?

**Comment by eddiejaoude** [comment]
Oh interesting 🤔 . Good spot 👍

**Comment by iamkumar-gaurav** [comment]
<p align="center">
  <img width="35%"src="https://github-readme-stats.vercel.app/api?username=eddiejaoude&show_icons=true&theme=tokyonight&line_height=52" />
  <img width="26.5%" src="https://github-readme-stats.vercel.app/api/top-langs/?username=eddiejaoude&count_private=true&theme=tokyonight&line_height=52" />
</p>

**Comment by adityaraute** [comment]
Can you explain your comment @iamkumar-gaurav ? I am not sure what your point is.

**Comment by iamkumar-gaurav** [comment]
sorry for that it was just for open issue #49 Card heights mismatched by mistake I sent the result here .so Sorry for the inconvenience i was just practicing

**Comment by eddiejaoude** [comment]
I think this is now fixed 👍
