### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/eddiejaoude#5]

**Comment by dumbcoder7** [comment]
Will try to solve this. Hope that is fine.

**Comment by eddiejaoude** [comment]
Great 👍 Thank you @dumbcoder7 that is awesome 🤓

**Comment by dumbcoder7** [comment]
The PR is now ready for review.

**Comment by adityaraute** [comment]
Consider closing this issue.

**Comment by eddiejaoude** [comment]
oh yes PR was merged, I will close 👍 thank you!
