### ISSUE TITLE
Links in Testimonials

### ISSUE THREAD

**Issue by adityaraute** [eddiejaoude/eddiejaoude#52]
![image](https://user-images.githubusercontent.com/43912470/106502268-2ae97580-64ea-11eb-8926-b410178d1278.png)
I absolutely dislike that the column of links, in the Testimonials section, is so wide that it takes away the most space.
We could maybe add an icon, preferably Twitter, and link each one to the respective tweet, to save space.

**Comment by eddiejaoude** [comment]
yes these should be improved

**Comment by eddiejaoude** [comment]
Improved 🤓 

<img width="1211" alt="Screenshot 2021-02-06 at 11 26 27" src="https://user-images.githubusercontent.com/624760/107116880-303e1b80-686e-11eb-8e77-fb288c17b826.png">

**Comment by adityaraute** [comment]
I was trying for a different style. Hope I manage to create a good PR

**Comment by eddiejaoude** [comment]
Sure, I am catching up with notifications, I will get to your PR soon 🤓

**Comment by adityaraute** [comment]
Hope I will get to it soon, too. 🤣

**Comment by eddiejaoude** [comment]
I have many to add still to my GitHub profile and also my website

**Comment by adityaraute** [comment]
Yeah, can't believe only 4 people praised you 😆

**Comment by eddiejaoude** [comment]
LOL 😜 always the joker 😂
