### ISSUE TITLE
Rename main.yml in github/workflows

### ISSUE THREAD

**Issue by abughurab16** [eddiejaoude/eddiejaoude#54]
# You mentioned that you need to change the file name

## It would be convenient to change it from "main.yml"  to something more descriptive.

**Comment by eddiejaoude** [comment]
Yes, thank you 👍

**Comment by lukeecart** [comment]
Hi, this is my first contribution. Just watched your Youtube video about this.
I've created a PR for this. 👍🏻

**Comment by eddiejaoude** [comment]
Thank you @lukeecart , PR accepted and merged 💥
