### ISSUE TITLE
Add some randomly picked testimonials.

### ISSUE THREAD

**Issue by Utkarsh299-tech** [eddiejaoude/eddiejaoude#61]
Can we have some randomly picked testimonials on your profile?

**Comment by adityaraute** [comment]
@eddiejaoude 's idea:
Create a JSON file with lots of testimonials
Create a GitHub Action to pick any 5 everyday and display on the profile.

**Comment by rhianeKobar** [comment]
Hey, I'd like to help solve this issue but I'm not sure I have the skills to yet. 
 
Are the testimonials coming from [Eddie's site](https://www.eddiejaoude.io/?r_done=1#_qbd5vru62)?

**Comment by eddiejaoude** [comment]
Thanks all 👍 

I have some on my site. But I should probably share the testimonials I have created, then
1. someone can create a json file
2. then from that we can do different things like have a GitHub Action put them in my profile etc

**Comment by eddiejaoude** [comment]
Here are some that I have collected

- https://twitter.com/eddiejaoude/status/1364720592621043718
- https://twitter.com/monkchips/status/1364550984106717190
- https://twitter.com/eddiejaoude/status/1356022828856987649
- https://twitter.com/urlichsanais/status/1349358736092094467
- https://twitter.com/yalematta/status/1304541107330658313
- https://twitter.com/__nawalhmw/status/1304572901140635648
- https://twitter.com/allanregush/status/1304484456221167617
- https://twitter.com/MikeRogers0/status/1304320638463741952
- https://twitter.com/eddiejaoude/status/1280063374932484097
- https://twitter.com/__nawalhmw/status/1304870527018979331?s=21
- https://twitter.com/yalematta/status/1304541107330658313?s=21
- Patrick Debois https://www.linkedin.com/feed/update/urn:li:activity:6711225360224202752?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6711225360224202752%2C6711645968451829760%29 
- https://twitter.com/adityad14206128/status/1306631921946914816?s=21
- https://github.blog/2020-08-30-github-action-hero-eddie-jaoude/
- https://github.blog/2020-09-03-introducing-the-github-stars-program/
- https://twitter.com/eddiejaoude/status/1311395059728887823
- https://twitter.com/eddiejaoude/status/1311599515854610432
- https://twitter.com/thatanimeguy23/status/1312473829877321730
- https://twitter.com/eddiejaoude/status/1312666272707026944
- https://twitter.com/eddiejaoude/status/1314133810968244224
- https://twitter.com/eddiejaoude/status/1320642071569534976
- https://twitter.com/lihautan/status/1331878791287750656
- https://twitter.com/ja9look/status/1331565025841074177
- GitHub Star of the year tweet https://twitter.com/github/status/1333923873713233922
- https://twitter.com/vinz_vinci/status/1338759776201633797
- https://twitter.com/eddiejaoude/status/1344406163513868289
- https://www.linkedin.com/feed/update/urn:li:activity:6750315988073398272/?commentUrn=urn%3Ali%3Acomment%3A(activity%3A6750315988073398272%2C6750347500542050304)&replyUrn=urn%3Ali%3Acomment%3A(activity%3A6750315988073398272%2C6750349725452558336) 
- https://twitter.com/vyvy_vim/status/1348043664375877632?s=21
- https://twitter.com/Anita_ihuman/status/1353991328607121413

**Comment by adityaraute** [comment]
That's a lot of tweets.

![image](https://user-images.githubusercontent.com/43912470/109390844-f5de1080-7939-11eb-83ad-90f9ee3efe1a.png)

**Comment by rhianeKobar** [comment]
Sweet, I'm glad this got updated. I've started the JSON file if anyone else wants to help https://jsonformatter.org/json-parser/df9d2a

**Comment by rhianeKobar** [comment]
I've made a JSON file https://jsonformatter.org/json-parser/0a607f I tried to upload but github wasn't having it haha. 
Should I push the .json I created to this repo?

Two of the testimonials are articles and I'm not sure how that would work so I left them out for now.
>https://github.blog/2020-08-30-github-action-hero-eddie-jaoude/
and
>https://github.blog/2020-09-03-introducing-the-github-stars-program/

There were also two testimonials unavailable
>https://twitter.com/vinz_vinci/status/1338759776201633797
and
>https://www.linkedin.com/feed/update/urn:li:activity:6750315988073398272/?commentUrn=urn%3Ali%3Acomment%3A(activity%3A6750315988073398272%2C6750347500542050304)&replyUrn=urn%3Ali%3Acomment%3A(activity%3A6750315988073398272%2C6750349725452558336)

**Comment by adityaraute** [comment]
Yes I think you should create a PR and push the JSON file.

**Comment by rhianeKobar** [comment]
Just created it..........very excited about doing my first PR :D :D :D

**Comment by adityaraute** [comment]
Please link the PR here.

**Comment by rhianeKobar** [comment]
[here it is](https://github.com/eddiejaoude/eddiejaoude/pull/66). It's this is what usually happens? Should you always link the PR in the issue?

**Comment by adityaraute** [comment]
No this doesn't help.
You have to write

> Fixes #61

In the comment of the PR (you can use the edit option, or add a new comment).

When you do this, this issue will automatically get closed after that PR is merged, thus making it easier for the project maintainer.
It's only a good practice.

**Comment by eddiejaoude** [comment]
Great collaboration everyone 👍 

I will close this because the PR is merged.

**Comment by rhianeKobar** [comment]
@adityaraute I only just understood what you meant, thanks for explaining :D next time I'll get it right
