### ISSUE TITLE
Youtube badge shows invaild 

### ISSUE THREAD

**Issue by AllanRegush** [eddiejaoude/eddiejaoude#67]
Youtube badge shows invalid

![Screenshot_20210301_122454](https://user-images.githubusercontent.com/17693494/109541556-8d9e4480-7a89-11eb-885d-6d1f1ffbaa27.png)

**Comment by eddiejaoude** [comment]
Hmm I just checked and it worked for me 🤔 . Maybe the service had some issues. Lets keep this open and keep an eye on it

**Comment by DevCassie** [comment]
Also says invalid for me.

**Comment by Frakko** [comment]
Same for me - it's invalid 🤔

**Comment by SashoStoichkov** [comment]
I also can confirm that it says `invalid`

**Comment by SashoStoichkov** [comment]
Now it seems to be working 👍🏻

**Comment by DevCassie** [comment]
> Now it seems to be working 👍🏻

Indeed, it works now for me too 👍

**Comment by schmelto** [comment]
Think this issues is moved to https://github.com/eddiejaoude/eddiejaoude/issues/83
