### ISSUE TITLE
Make Hashtags bold

### ISSUE THREAD

**Issue by sangeetagupta2068** [eddiejaoude/eddiejaoude#7]
Making hashtags bold will help grab a new person's attention to the things you are passionate about.

**Comment by eddiejaoude** [comment]
Great idea and possibly add a link to twitter?

**Comment by sangeetagupta2068** [comment]
Do you want to add individual links for the topics? Was suggesting to make the following bold : #code #github #remote #startup & #inclusion

**Comment by eddiejaoude** [comment]
I think individual links would be great, but that can be done in another PR - then you can get 2 (if you like). I definitely prefer small incremental changes, the smaller the better 🤓

**Comment by sangeetagupta2068** [comment]
Hi Eddie, I have submitted a PR with the hyperlinks to hashtags. Can you please review?

**Comment by eddiejaoude** [comment]
oh sorry @sangeetagupta2068 I think I missed it 🤦‍♂️ 

Thank you for the PR and the reminder, I will review now 👍

**Comment by eddiejaoude** [comment]
@sangeetagupta2068 I shared a screenshot from a live stream, that I think was showing your message. What is your twitter so I can mention you 🤓  https://twitter.com/eddiejaoude/status/1287307869097021440

**Comment by sangeetagupta2068** [comment]
Thank you so much! That would be awesome! It's sangee_2068

**Comment by sangeetagupta2068** [comment]
@eddiejaoude I have added the required changes. Can you review it once?
