### ISSUE TITLE
Add Links to Website in Read Me ! 

### ISSUE THREAD

**Issue by rohank2502** [eddiejaoude/eddiejaoude#72]
Link to the @eddiejaoude  website or link to the newsletter is missing! We can add those so that it will be more convenient for everyone to have a look at the website/news letter in the future.

Newsletter :- https://t.co/Hl62uM4W4t?amp=1
Website :- https://www.eddiejaoude.io/ 

@eddiejaoude  will let you know where to add those !!

**Comment by toth2000** [comment]
I will be happy to work on this issue.

**Comment by eddiejaoude** [comment]
Great idea @rohank2502 👍 

Yes please @toth2000 , that would be great.

Maybe above the badges, something like this...

```html
<p align="center">
  For more information, have a look at <b>Eddie's websiteEddieHub</b> <a href="http://eddiejaoude.io">eddiejaoude.io</a>
  and also the <a href="http://eddiejaoude.io/newsletters">newsletters</a>
</p>
```

**Comment by eddiejaoude** [comment]
Thank you 👍

**Comment by eddiejaoude** [comment]
Done 👍

**Comment by rohank2502** [comment]
Thanks for your contribution @toth2000 !!
