### ISSUE TITLE
Adding  line so we can create testimonial a diffrent section ! 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [eddiejaoude/eddiejaoude#76]
![Screenshot 2021-05-03 225821](https://user-images.githubusercontent.com/76584243/116910337-22c4e180-ac63-11eb-8ba2-407d67dadb87.png)

WE can add `<hr>` above testimonial so that it can be made a separate section !!

**Comment by eddiejaoude** [comment]
thank you for the suggestion, now the widgets have been removed, I think this is no longer needed
