### ISSUE TITLE
Include less words in Table

### ISSUE THREAD

**Issue by harekrishnarai** [eddiejaoude/eddiejaoude#78]
Table has more words in sentences in right side which fills up the screen after opening in Mobile View.

**Comment by eddiejaoude** [comment]
Thanks for raising, can you share a screenshot?

**Comment by ShlokMohanty** [comment]
![image](https://user-images.githubusercontent.com/59838234/133675748-cfc25e1f-e402-4943-9193-cb5aacfef050.png)

@eddiejaoude is @harekrishnarai talking about the bottom most table on this github page ?

**Comment by eddiejaoude** [comment]
But it looks ok here? I think the issue was about mobile?
