### ISSUE TITLE
change the link on the banner to https://www.eddiejaoude.io/

### ISSUE THREAD

**Issue by schmelto** [eddiejaoude/eddiejaoude#79]
Think the link on the banner is wrong.

![image](https://user-images.githubusercontent.com/30869493/116910730-4cbbdb00-ac46-11eb-8507-a2d1a6539e95.png)

I think this should be https://www.eddiejaoude.io/

**Comment by eddiejaoude** [comment]
Thank you 👍

**Comment by eddiejaoude** [comment]
Fixed 🎉
