### ISSUE TITLE
[FEATURE] : Adding 🌟 at the end of 'GitHub star section'

### ISSUE THREAD

**Issue by kulendu** [eddiejaoude/eddiejaoude#81]
I think adding 🌟 at the end of 'GitHub star section' si really a simple add-on. Hope you like it

![image](https://user-images.githubusercontent.com/56751963/116910875-dc23b700-ac63-11eb-8204-a62d917645d2.png)

My network is really bad, or else I would have been adding a screenshot

**Comment by eddiejaoude** [comment]
Thank you for raising 👍

**Comment by eddiejaoude** [comment]
Merged here https://github.com/eddiejaoude/eddiejaoude/pull/82#pullrequestreview-650572956
