### ISSUE TITLE
add new banner to README

### ISSUE THREAD

**Issue by starlightknown** [eddiejaoude/eddiejaoude#86]
**_This is how it'll look_**
![look](https://user-images.githubusercontent.com/74637789/116991596-661a6100-acf2-11eb-9e29-6ba50996557e.png)

**Replace the old banner with the new one.**
Banner Links Below:
[banner gif-no-text](https://github.com/EddieHubCommunity/Branding/blob/main/community/Eddie_banner_GIF.gif)

[banner-static-no-text](url)

**Comment by eddiejaoude** [comment]
Yes this will be great 👍
