### ISSUE TITLE
YouTube video list

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/eddiejaoude#89]
https://github.com/natterstefan/natterstefan/blob/master/.github/workflows/youtube-videos-workflow.yml

**Comment by vikasganiga05** [comment]
Hi @eddiejaoude , The workflow to list youtube videos is already added - [.github/workflows/youtube.yml](https://github.com/eddiejaoude/eddiejaoude/blob/main/.github/workflows/youtube.yml) by you on Dec 1, 2021. I think you forgot to close this issue :thinking: .

**Comment by eddiejaoude** [comment]
oh yes! Thank you Vikas! 👍
